Repository kottans/mock-repo, pull requests merged in 2020-10, with the labels that each got.

#440 Update README.md
  README.md
Labels: Request changes

#439 Update readme.md: greeting
  README.md
Labels: waiting for approval

#442 Update README.md
  README.md
Labels: waiting for approval

#438 send greeting to kottans
  README.md
Labels: request changes

#477 Update README.md
  README.md
Labels: request changes

#430 Update Readme.md from Andrew Klmn with text and picture
  README.md
Labels: request changes

#475 Added introduction about myself (user Nallikaea)
  README.md
  assets/images/Sergiy.jpg
Labels: request changes

#508 about me info added to readme.md
  README.md
  assets/images/PngItem_30125.png
Labels: request changes

#467 Fix typo in README
  README.md
  assets/images/my_cat.jpg
Labels: request changes
